# Generated by Django 4.2.7 on 2023-12-03 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_remove_contact_birthday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='full_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='relationship',
            new_name='last_name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='address',
        ),
    ]
